version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_SERVER_HOST=db
      - DB_SERVER_PORT=3306
      - DB_SERVER_USERNAME=root
      - DB_SERVER_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=papafoot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "--character-set-server=utf8mb4  --max_allowed_packet=1048576"
    ports:
      - "3306:3306"