spring:
  application:
    name: "papafood-backend"
  jmx:
    enabled: false
  mvc:
    async:
      request-timeout: -1
  jackson:
    serialization:
      write_dates_as_timestamps: false

datasource:
  models_master:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_SERVER_HOST:localhost}:${DB_SERVER_PORT:3306}/papa_food?useSSL=false&allowPublicKeyRetrieval=true"
    username: "${DB_SERVER_USERNAME:root}"
    password: "${DB_SERVER_PASSWORD:root}"
    initialSize: 10
    minIdle: 5
    maximumPoolSize: 20
    showSql: true
    batchSize: 20

security:
  header: Authorization
  token:
    timeoutHours: 24